-- Flowtask: Login-Verlauf + Passwort-Reset-Unterstützung
-- Einmal im Supabase SQL Editor ausführen.

create table if not exists public.flowtask_login_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  logged_in_at timestamptz not null default now(),
  user_agent text
);

create index if not exists flowtask_login_logs_logged_in_at_idx
  on public.flowtask_login_logs (logged_in_at desc);

alter table public.flowtask_login_logs enable row level security;

-- Jeder angemeldete Benutzer darf seinen eigenen Login protokollieren.
drop policy if exists "flowtask login insert own" on public.flowtask_login_logs;
create policy "flowtask login insert own"
on public.flowtask_login_logs
for insert
to authenticated
with check (auth.uid() = user_id);

-- Nur Flowtask-Administratoren dürfen den gesamten Verlauf lesen.
drop policy if exists "flowtask admin read login logs" on public.flowtask_login_logs;
create policy "flowtask admin read login logs"
on public.flowtask_login_logs
for select
to authenticated
using (public.is_flowtask_admin());

-- Falls die vorhandene Admin-Funktion noch keine SECURITY DEFINER-Funktion ist,
-- bitte die bereits vorhandene Admin-Funktion nicht überschreiben. Sie muss lediglich
-- für die SELECT-Policy funktionieren.

-- Passwort-Zurücksetzung läuft über Supabase Auth:
-- Die HTML-App verwendet resetPasswordForEmail() und updateUser({password: ...}).
-- Dafür sind keine Passwort-Hashes in einer eigenen Tabelle erforderlich.
